name: mightyweb
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # BASE
  nb_utils: ^6.0.6
  google_fonts: ^6.1.0
  lottie: ^2.6.0
  gap: ^3.0.1
  flutter_screenutil: ^5.9.3
  # firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  get: ^4.6.5


  # UI
  cached_network_image: ^3.3.0
  flutter_spinkit: ^5.2.0
  package_info_plus: ^4.2.0
  flutter_speed_dial: ^7.0.0
  flutter_native_splash: ^2.3.5

  # STATE MANAGEMENT
  mobx: ^2.2.1
  flutter_mobx: ^2.1.1

  # STORAGE & PERMISSION
  path_provider: ^2.1.1
  provider: ^6.0.5

  # CONNECTIVITY
  http: ^1.1.0
  share_plus: ^7.2.1
  store_redirect: ^2.0.1

  # Firebase
  firebase_core: 3.13.0
  firebase_messaging: ^15.2.5
  flutter_inappwebview: ^5.3.2
  permission_handler: ^10.2.0
  url_launcher: ^6.1.8

  # PUSH NOTIFICATION
  onesignal_flutter: ^5.0.3

  # ADS
  google_mobile_ads: ^3.1.0
  #facebook_audience_network: ^1.0.1

  # WEB TOOLS
  qr_code_scanner: ^1.0.1

  flutter_localizations:
    sdk: flutter

  # Connectivity and Network
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1
  firebase_messaging_web: ^3.5.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - lang/
