// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4QHHuYIniQ3OG7ABixODUpd4zWICvoAA',
    appId: '1:642620604314:web:79d6578cee06c439238423',
    messagingSenderId: '642620604314',
    projectId: 'migh-45fb9',
    authDomain: 'migh-45fb9.firebaseapp.com',
    storageBucket: 'migh-45fb9.firebasestorage.app',
    measurementId: 'G-5G6XJ5YS1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkbW8PLTmOTWFwhfu7aDz0qrb21jBmPM0',
    appId: '1:642620604314:android:af85dfab75f6584b238423',
    messagingSenderId: '642620604314',
    projectId: 'migh-45fb9',
    storageBucket: 'migh-45fb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZVwIFa-oPOCD-NuhVSdwEY75i2CTN67M',
    appId: '1:642620604314:ios:2fd509b7a7f77a7e238423',
    messagingSenderId: '642620604314',
    projectId: 'migh-45fb9',
    storageBucket: 'migh-45fb9.firebasestorage.app',
    iosBundleId: 'com.mighty.web',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZVwIFa-oPOCD-NuhVSdwEY75i2CTN67M',
    appId: '1:642620604314:ios:f9206bc95438d7d4238423',
    messagingSenderId: '642620604314',
    projectId: 'migh-45fb9',
    storageBucket: 'migh-45fb9.firebasestorage.app',
    iosBundleId: 'com.mighty.weblyFlutter',
  );
}
